name: Simple Test with JWT
#on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run tests
        run: |
          echo "Executando testes da aplicação JSX..."
           exit 1 
          
      # JWT para criar uma issue se falhar
      - name: Generate Token
        if: failure()
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Falha no pipeline de testes',
              body: `Commit ${context.sha} falhou nos testes.\n\nVerifique: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}`,
              labels: ['bug', 'ci-failure']
            });